### ISSUE TITLE
Running time of RUN_Iterated.m

### ISSUE THREAD

**Issue by srsohn** [iqbalu/3D_Pose_Estimation_CVPR2016#4]
Hi-
I have some questions about the programs.
1. Are RUN_Iterated.m and RUN_Complete.m producing the same result?
2. Which one is faster? RUN_Iterated.m or RUN_Complete.m?
3. It takes quite a long time(>20min) for me to get a result for a single image. (running RUN_Iterated.m)
Can I ask you the running time of RUN_Iterated.m for a single image?
I guess the reported time on paper is based on the program that uses more than 100G of RAM and this program might be slower than that because it's using less than 30G of RAM.
If this is the case, can you upload the original version of program that uses 100G of RAM?

Best Regards.

**Comment by umariqb** [comment]
Hi,
1. Yes, they should produce same results. Let me explain you the difference. If you have read the paper, you can see that the nearest neighbors are retrieved based on five different joint sets, so we require five different databases of 3D poses. In RUN_Iterated.m all five databases, one at a time in this version, are loaded into the memory to perform retrieval for each joint type. This is done for every test image. Once we have nearest neighbors for all joint sets, we are ready to perform the rest of the steps for pose reconstruction. However, in RUN_Complete.m we load one database in the memory, and perform retrieval for all test images. This step is repeated five times, and we obtain nearest neighbors for all joint sets and all test images. 
2. RUN_Iterated.m is good for understanding since it processes the complete pipeline for a single image. However, RUN_Complete.m is good for batch processing, since the databases are loaded only once for all images. This is in contrast to RUN_Iterated.m where the databases are loaded for each image separately. 
3. Yes, depending on your machine, it can take this much time. This is mainly due to loading the databases into memory. In the paper, we do not consider the time required for loading the database, since in the original version this was done only once. 

Providing the original version of the code will not be possible at this point since requires some refactoring. However, we are hoping to release an improved version of the code roughly in December this year. 

Hope that helps

**Comment by srsohn** [comment]
Okay.
Now everything is quite clear!
Thanks.

Best regards.
